FROM alpine:3.17

ARG USER_FTP \
    PASS_FTP

RUN apk update && apk add vsftpd

RUN adduser -h /var/www -s /bin/false -D ${USER_FTP} && \
    echo "${USER_FTP}:${PASS_FTP}" | /usr/sbin/chpasswd && \
    adduser ${USER_FTP} root

RUN sed -i "s|#chroot_local_user=YES|chroot_local_user=YES|g"  /etc/vsftpd/vsftpd.conf && \
    sed -i "s|#local_enable=YES|local_enable=YES|g"  /etc/vsftpd/vsftpd.conf && \
    sed -i "s|#write_enable=YES|write_enable=YES|g"  /etc/vsftpd/vsftpd.conf && \
    sed -i "s|#local_umask=022|local_umask=007|g"  /etc/vsftpd/vsftpd.conf

RUN echo "allow_writeable_chroot=YES" >> /etc/vsftpd/vsftpd.conf &&\
    echo 'seccomp_sandbox=NO' >> /etc/vsftpd/vsftpd.conf && \
    echo 'pasv_enable=YES' >> /etc/vsftpd/vsftpd.conf

WORKDIR /var/www

EXPOSE 21

CMD ["vsftpd", "/etc/vsftpd/vsftpd.conf"]